name: Publish Docker to ECR
description: Builds and publishes docker image to AWS ECR
author: itsmycargo
branding:
  color: blue
  icon: layers

inputs:
  repository:
    description: ECR Repository to use for Images
    required: true
  registry_password:
    description: 'Password for image registry'
    required: true
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
    default: '.'
  path-to-dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: './Dockerfile' 
  aws-access-key-id:
    description: AWS Access Key ID for login and pushing to ECR Repository
    required: true
  aws-secret-access-key:
    description: AWS Access Key for login and pushing to ECR Repository
    required: true
  aws-region:
    description: AWS Region for ECR Repository
    required: true

outputs:
  repositoryTag:
    description: Published Docker Image with Tag
    value: ${{ steps.meta.outputs.repositoryTag }}
  repository:
    description: Published Docker Image
    value: ${{ steps.meta.outputs.repository }}
  tag:
    description: Published Docker Tag
    value: ${{ steps.meta.outputs.tag }}

runs:
  using: "composite"
  steps:
    - id: meta
      uses: itsmycargo/docker-meta-action@main
      with:
        repository: ${{ inputs.repository }}

    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - uses: aws-actions/amazon-ecr-login@v1
    - uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.path-to-dockerfile }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          RELEASE=${{ github.sha }}
